name: Build Binaries

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    container:
      image: node:lts

    steps:
      - uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Ignore Husky
        run: npm set-script prepare ""

      - name: npm install
        run: npm install

      - name: npm cache clear --force
        run: npm cache clear --force

      - name: npm cache rm
        run: npm cache rm --force

      - name: npm cache verify
        run: npm cache verify

      - name: install global packages
        run: npm i -g @babel/cli @babel/preset-env pkg

      - name: create distributions
        run: npm run create-distribution

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ${{ github.workspace }}/dist

      - name: Get list of files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          file_list=$(find ./dist -type f)
          echo "::set-output name=file-list::$file_list"
        id: file-list

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.file-list.outputs.file-list }}
