name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    name: NPM Tests
    runs-on: ubuntu-latest
    container:
      image: node:20.16

    steps:
      - uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ignore Husky
        run: npm pkg delete scripts.prepare

      - name: Install Mocha
        run: npm install --save-dev mocha

      - name: npm install
        run: npm install

      - name: npm cache clear --force
        run: npm cache clear --force

      - name: npm cache rm
        run: npm cache rm --force

      - name: npm cache verify
        run: npm cache verify

      - name: install global packages
        run: npm i -g @babel/cli sequelize-cli cross-env

      - name: npm tests
        run: npm run test

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    container:
      image: node:20.16

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Chia and chia-tools
        shell: bash
        run: |
          apt-get install -y ca-certificates curl gnupg

          curl -sL https://repo.chia.net/FD39E6D3.pubkey.asc | gpg --dearmor -o /usr/share/keyrings/chia.gpg

          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/debian/ stable main" | tee /etc/apt/sources.list.d/chia.list > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/chia-tools/debian/ stable main" | tee /etc/apt/sources.list.d/chia-tools.list > /dev/null
          apt-get update

          apt-get install -y chia-blockchain chia-tools

      - name: Configure Chia
        shell: bash
        run: |
          chia init
          chia keys generate -l "functional_tests"
          chia-tools network switch testneta
          chia-tools config add-trusted-peer -y 54.214.229.33

      - name: Run tests
        shell: bash
        run: |
          chia start wallet data
          sleep 60
          cat ~/.chia/mainnet/log/debug.log
          chia stop all -d
